[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM5
monitor_port = COM5

lib_ldf_mode = deep+
build_src_filter =
    +<main.cpp>
    +<DeskRoboMVP.cpp>
    +<DeskRoboWeb.cpp>
    +<anime_face.cpp>
    +<LVGL_Arduino/Display_ST77916.cpp>
    +<LVGL_Arduino/esp_lcd_st77916.c>
    +<LVGL_Arduino/LVGL_Driver.cpp>
    +<LVGL_Arduino/I2C_Driver.cpp>
    +<LVGL_Arduino/TCA9554PWR.cpp>
    +<LVGL_Arduino/Gyro_QMI8658.cpp>
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DCORE_DEBUG_LEVEL=3
    -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Network/src
    ; -DDESKROBO_ENABLE_GYRO=1
    ; -DDESKROBO_GYRO_EVENTS=1
    ; -DDESKROBO_SHOW_DEBUG=1
    ; enable if you know the board microphone ADC pin, e.g. -DDESKROBO_AUDIO_ADC_PIN=1
