#pragma once

#include <Arduino.h>

typedef enum {
  DESKROBO_EMOTION_IDLE = 0,
  DESKROBO_EMOTION_HAPPY,
  DESKROBO_EMOTION_SAD,
  DESKROBO_EMOTION_ANGRY,
  DESKROBO_EMOTION_ANGST,
  DESKROBO_EMOTION_WOW,
  DESKROBO_EMOTION_SLEEPY,
  DESKROBO_EMOTION_LOVE,
  DESKROBO_EMOTION_CONFUSED,
  DESKROBO_EMOTION_EXCITED,
  DESKROBO_EMOTION_ANRUF,
  DESKROBO_EMOTION_LAUT,
  DESKROBO_EMOTION_MAIL,
  DESKROBO_EMOTION_DENKEN,
  DESKROBO_EMOTION_WINK,
  DESKROBO_EMOTION_GLITCH,
} DeskRoboEmotion;

typedef enum {
  DESKROBO_EVENT_NONE = 0,
  DESKROBO_EVENT_AUDIO_QUIET,
  DESKROBO_EVENT_AUDIO_LOUD,
  DESKROBO_EVENT_AUDIO_VERY_LOUD,
  DESKROBO_EVENT_MOTION_TILT,
  DESKROBO_EVENT_MOTION_SHAKE,
  DESKROBO_EVENT_PC_CALL,
  DESKROBO_EVENT_PC_MAIL,
  DESKROBO_EVENT_PC_TEAMS,
} DeskRoboEventType;

void DeskRobo_Init();
void DeskRobo_Loop();
void DeskRobo_PushEvent(DeskRoboEventType event_type);
DeskRoboEmotion DeskRobo_GetEmotion();
void DeskRobo_SetEmotion(DeskRoboEmotion emotion, uint32_t hold_ms);
